# Use an official Node.js image as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app/backend

# Copy package.json and package-lock.json to the container
COPY ./backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the local source files to the container
COPY ./backend .

# Expose the port that Express will run on
EXPOSE 5000

# Start the Express app
CMD ["npm", "start"]
