# Use an official Node.js image as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app/frontend

# Copy package.json and package-lock.json to the container
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the local source files to the container
COPY ./frontend .

# Expose the port that Next.js will run on
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "run", "dev"]
